---
sudo: false
language: ruby
before_install:
  - gem install bundler --version $BUNDLER_VERSION
install: bundle _${BUNDLER_VERSION}_ install --retry 5
script: bundle _${BUNDLER_VERSION}_ exec rspec --color --format documentation
notifications:
  email: true
rvm:
  - 2.2.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - VAGRANT_VERSION=1.5.0 BUNDLER_VERSION=1.5.2
    - VAGRANT_VERSION=1.6.5 BUNDLER_VERSION=1.6.9
    - VAGRANT_VERSION=1.7.0 BUNDLER_VERSION=1.7.9
    - BUNDLER_VERSION=1.7.9
